version: "2.1"

services:
  testing_service:
    build: "./"
    image: "$IMAGE_NAME:$IMAGE_TAG"
    ports:
      - "1234"

  testing_service_healthy:
    build: "./"
    image: "${IMAGE_NAME}_healty:$IMAGE_TAG"
    ports:
      - "1234"
    healthcheck:
      test: ["CMD", "healthy-healthcheck.sh"]
      interval: 2s
      timeout: 2s
      retries: 3

  testing_service_unhealthy:
    build: "./"
    image: "${IMAGE_NAME}_unhealty:$IMAGE_TAG"
    ports:
      - "1234"
    healthcheck:
      test: ["CMD", "unhealthy-healthcheck.sh"]
      interval: 2s
      timeout: 2s
      retries: 3
